### PR TITLE
Changed "mission" & "why join?"

### PR DESCRIPTION
**Pull request by MadhavPK**
https://madhavpk.github.io/Project-Oslo/

### CODE REVIEW

**Comment by whiplash7** [comment]
Seems alright.

**Review by vipulchodankar — APPROVED** [review]
Seems alright, i approve.

**Review by adityachanekar — APPROVED** [review]
Looks good enough.

**Comment by aven99** [comment]
Seems fine.

**Review by kevinam99 — APPROVED** [review]
Approved. Merged to master.

**Pull request merged**
